import { ChangeEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { t } from '@ankr.com/common';

export interface UseTeamNameInputParams {
  teamName?: string;
}

export const useTeamNameInput = ({ teamName }: UseTeamNameInputParams) => {
  const defaultValue = useMemo(() => {
    const defaultTeamName = t('teams.create-team-form.default-team-name');

    // last 4 digits of the current timestamp
    const teamId = Date.now().toString().slice(-4);

    const autoGeneratedName = `${teamName || defaultTeamName} #${teamId}`;

    return autoGeneratedName;
  }, [teamName]);

  const [teamNameValue, setTeamNameValue] = useState(defaultValue);

  useEffect(() => {
    setTeamNameValue(defaultValue);
  }, [defaultValue]);

  const handleChange = useCallback((event: ChangeEvent<HTMLInputElement>) => {
    setTeamNameValue(event.target.value);
  }, []);

  return {
    teamNameValue,
    handleChange,
  };
};
