export const CHAINS_MOCK = [
  {
    chainLogo: 'https://assets.ankr.com/charts/icon-only/ethereum.svg',
    name: 'eth',
    requestInfo: '3 472 952 req',
    period: '24h',
    chainLink: 'https://mrpc.com/ethereum',
    chainDetailsLink: '/chains/ethereum',
  },
  {
    chainLogo: 'https://assets.ankr.com/charts/icon-only/binance.svg',
    name: 'binance',
    requestInfo: '3 472 952 req',
    period: '24h',
    chainLink: 'https://mrpc.com/binance',
    chainDetailsLink: '/chains/binance',
  },
  {
    chainLogo: 'https://assets.ankr.com/charts/icon-only/okchain.svg',
    name: 'okchain',
    requestInfo: '3 472 952 req',
    period: '24h',
    chainLink: 'https://mrpc.com/okchain',
    chainDetailsLink: '/chains/okchain',
  },
  {
    chainLogo: 'https://assets.ankr.com/charts/icon-only/polkadot.svg',
    name: 'polkadot',
    requestInfo: '3 472 952 req',
    period: '24h',
    chainLink: 'https://mrpc.com/polkadot',
    chainDetailsLink: '/chains/polkadot',
  },
  {
    chainLogo: 'https://assets.ankr.com/charts/icon-only/kusama.svg',
    name: 'kusama',
    requestInfo: '3 472 952 req',
    period: '24h',
    chainLink: 'https://mrpc.com/kusama',
    chainDetailsLink: '/chains/kusama',
  },
  {
    chainLogo: 'https://assets.ankr.com/charts/icon-only/arbitrum.svg',
    name: 'arbitrum',
    requestInfo: '3 472 952 req',
    period: '24h',
    chainLink: 'https://mrpc.com/arbitrum',
    chainDetailsLink: '/chains/arbitrum',
  },
  {
    chainLogo: 'https://assets.ankr.com/charts/icon-only/xdai.svg',
    name: 'xdai',
    requestInfo: '3 472 952 req',
    period: '24h',
    chainLink: 'https://mrpc.com/xdai',
    chainDetailsLink: '/chains/xdai',
  },
];
