import { Token, TToken } from '../types/token';

// todo: STAKAN-2338 remove after migration to new tokens
export const tokenRenameMap: Record<Token, TToken> = {
  [Token.ANKR]: 'ANKR',
  [Token.ETH]: 'ETH',
  [Token.aETHb]: 'aETHb',
  [Token.aETH]: 'aETH',
  [Token.aETHc]: 'ankrETH',
  [Token.asETHc]: 'asETHc',
  [Token.AVAX]: 'AVAX',
  [Token.aAVAXb]: 'aAVAXb',
  [Token.aAVAXc]: 'ankrAVAX',
  [Token.MATIC]: 'MATIC',
  [Token.aMATICb]: 'aMATICb',
  [Token.aMATICc]: 'ankrMATIC',
  [Token.BNB]: 'BNB',
  [Token.aBNBb]: 'aBNBb',
  [Token.aBNBc]: 'ankrBNB',
  [Token.FTM]: 'FTM',
  [Token.aFTMb]: 'aFTMb',
  [Token.aFTMc]: 'ankrFTM',
  [Token.DOT]: 'DOT',
  [Token.aDOTb]: 'aDOTb',
  [Token.KSM]: 'KSM',
  [Token.aKSMb]: 'aKSMb',
  [Token.WND]: 'WND',
  [Token.aWNDb]: 'aWNDb',
  [Token.mGNO]: 'mGNO',
  [Token.xDAI]: 'xDAI',
  [Token.SUI]: 'SUI',
  [Token.ankrSUI]: 'ankrSUI',
  [Token.ankrXDC]: 'ankrXDC',
  [Token.XDC]: 'XDC',
};
