export enum SettingsContentState {
  DEFAULT = 'DEFAULT',
  LOADING = 'LOADING',
  CONNECT_WALLET = 'CONNECT_WALLET',
  LINK_EXPIRED = 'LINK_EXPIRED',
  ADD_EMAIL_FORM = 'ADD_EMAIl_FORM',
  ADD_EMAIL_SUCCESS = 'ADD_EMAIL_SUCCESS',
  SETTINGS = 'SETTINGS',
}
