export enum ChainId {
  Avalanche = 'avalanche',
  Arbitrum = 'arbitrum',
  BSC = 'bsc',
  Celo = 'celo',
  Ethereum = 'eth',
  Fantom = 'fantom',
  Harmony = 'harmony',
  IoTeX = 'iotex',
  Near = 'near',
  Nervos = 'nervos',
  Nervos_GW = 'nervos_gw',
  Polygon = 'polygon',
  Solana = 'solana',
  Erigonbsc = 'erigonbsc',
}
