export type DeFiItem = {
  assets: string;
  network: string;
  protocol: string;
  type: string;
  rewardedToken: string;
  protocolLink: string;
};

export const useDeFiData = (): DeFiItem[] => [
  {
    assets: 'aETHb/ETH',
    type: 'Liquidity Pool',
    rewardedToken: 'aETHb/ETH',
    protocol: 'ACryptoS',
    network: 'BNB Chain',
    protocolLink: 'https://app.acryptos.com/stableswap/deposit/aethb/',
  },
  {
    assets: 'aETHb/ETH ACryptoS LP',
    type: 'Vault',
    rewardedToken: 'aETHb/ETH',
    protocol: 'ACryptoS',
    network: 'BNB Chain',
    protocolLink: 'https://app.acryptos.com/stableswap/deposit/aethb/',
  },
  {
    assets: 'aETHc/ETH Curve LP',
    type: 'Farming',
    rewardedToken: 'aethCRV',
    protocol: 'Convex Finance',
    network: 'Ethereum',
    protocolLink: 'https://www.convexfinance.com/stake',
  },
  {
    assets: 'aETHc/ETH',
    type: 'Liquidity Pool',
    rewardedToken: 'aETHc/ETH',
    protocol: 'Curve Finance',
    network: 'Ethereum',
    protocolLink: 'https://curve.fi/ankreth/',
  },
  {
    assets: 'aETHb/ETH',
    type: 'Liquidity Pool',
    rewardedToken: 'aETHb/ETH',
    protocol: 'Curve Finance',
    network: 'Ethereum',
    protocolLink: 'https://curve.fi/ankreth/',
  },
  {
    assets: 'aETHb/ETH',
    type: 'Liquidity Pool',
    rewardedToken: 'aETHb/ETH',
    protocol: 'Ellipsis Finance',
    network: 'BNB Chain',
    protocolLink: 'https://ellipsis.finance/pool/15',
  },
  {
    assets: 'aETHb/ETH Ellipsis LP',
    type: 'Farming',
    rewardedToken: 'EPX',
    protocol: 'Ellipsis Finance',
    network: 'BNB Chain',
    protocolLink: 'https://ellipsis.finance/pool/15',
  },
  {
    assets: 'aETHc/ETH SushiSwap LP',
    type: 'Vault',
    rewardedToken: 'aETHc/ETH',
    protocol: 'OnX Finance',
    network: 'Ethereum',
    protocolLink: 'https://app.onx.finance/vaults',
  },
  {
    assets: 'aETHc/ETH',
    type: 'Liquidity Pool',
    rewardedToken: 'aETHc/ETH',
    protocol: 'SushiSwap',
    network: 'Ethereum',
    protocolLink:
      'https://analytics.sushi.com/pairs/0xfa5bc40c3bd5afa8bc2fe6b84562fee16fb2df5f',
  },
  {
    assets: 'aETHc/ETH SushiSwap LP',
    type: 'Farming',
    rewardedToken: 'SUSHI',
    protocol: 'SushiSwap',
    network: 'Ethereum',
    protocolLink:
      'https://analytics.sushi.com/pairs/0xfa5bc40c3bd5afa8bc2fe6b84562fee16fb2df5f',
  },
  {
    assets: 'aETHc/ETH',
    type: 'Liquidity Pool',
    rewardedToken: 'aETHc/ETH',
    protocol: 'Uniswap v2',
    network: 'Ethereum',
    protocolLink:
      'https://v2.info.uniswap.org/pair/0x6147805e1011417b93e5d693424a62a70d09d0e5',
  },
  {
    assets: 'aETHc/ETH',
    type: 'Liquidity Pool',
    rewardedToken: 'aETHc/ETH',
    protocol: 'Uniswap v3',
    network: 'Ethereum',
    protocolLink:
      'https://info.uniswap.org/#/tokens/0xe95a203b1a91a908f9b9ce46459d101078c2c3cb',
  },
  {
    assets: 'aETHc/ETH Curve LP',
    type: 'Vault',
    rewardedToken: 'aETHc/ETH',
    protocol: 'Yearn Finance',
    network: 'Ethereum',
    protocolLink:
      'https://yearn.finance/#/vault/0x132d8D2C76Db3812403431fAcB00F3453Fc42125',
  },

  {
    assets: 'aETHb/ETH',
    type: 'Liquidity Pool',
    rewardedToken: 'aETHb/ETH',
    protocol: 'ACryptoS',
    network: 'BNB Chain',
    protocolLink: 'https://app.acryptos.com/stableswap/deposit/aethb/',
  },
  {
    assets: 'aBNBb/BNB',
    type: 'Liquidity Pool',
    rewardedToken: 'aBNBb/BNB',
    protocol: 'ACryptoS',
    network: 'BNB Chain',
    protocolLink: 'https://app.acryptos.com/stableswap/deposit/aethb/',
  },
  {
    assets: 'aBNBb/BNB ACryptoS LP',
    type: 'Vault',
    rewardedToken: 'aBNBb/BNB',
    protocol: 'ACryptoS',
    network: 'BNB Chain',
    protocolLink: 'https://app.acryptos.com/stableswap/deposit/aethb/',
  },
  {
    assets: 'aETHb/ETH ACryptoS LP',
    type: 'Vault',
    rewardedToken: 'aETHb/ETH',
    protocol: 'ACryptoS',
    network: 'BNB Chain',
    protocolLink: 'https://app.acryptos.com/stableswap/deposit/aethb/',
  },
  {
    assets: 'aBNBc/BNB',
    type: 'Liquidity Pool',
    rewardedToken: 'aBNBc/BNB',
    protocol: 'ApeSwap',
    network: 'BNB Chain',
    protocolLink: 'https://apeswap.finance/farms',
  },
  {
    assets: 'aBNBc/BNB ApeSwap LP',
    type: 'Farming',
    rewardedToken: 'BANANA',
    protocol: 'ApeSwap',
    network: 'BNB Chain',
    protocolLink: 'https://apeswap.finance/farms',
  },
  {
    assets: 'aBNBc/BNB PancakeSwap LP',
    type: 'Vault',
    rewardedToken: 'CAKE',
    protocol: 'Beefy Finance',
    network: 'BNB Chain',
    protocolLink: 'https://app.beefy.finance/#/bsc/vault/cakev2-wbnb-abnbc',
  },
  {
    assets: 'aETHb/ETH',
    type: 'Liquidity Pool',
    rewardedToken: 'aETHb/ETH',
    protocol: 'Ellipsis Finance',
    network: 'BNB Chain',
    protocolLink: 'https://ellipsis.finance/pool/15',
  },
  {
    assets: 'aBNBb/BNB',
    type: 'Liquidity Pool',
    rewardedToken: 'aBNBb/BNB',
    protocol: 'Ellipsis Finance',
    network: 'BNB Chain',
    protocolLink: 'https://ellipsis.finance/pool/15',
  },
  {
    assets: 'aBNBb/BNB Ellipsis LP',
    type: 'Farming',
    rewardedToken: 'EPX',
    protocol: 'Ellipsis Finance',
    network: 'BNB Chain',
    protocolLink: 'https://ellipsis.finance/pool/15',
  },
  {
    assets: 'aETHb/ETH Ellipsis LP',
    type: 'Farming',
    rewardedToken: 'EPX',
    protocol: 'Ellipsis Finance',
    network: 'BNB Chain',
    protocolLink: 'https://ellipsis.finance/pool/15',
  },
  {
    assets: 'aBNBc/BNB',
    type: 'Liquidity Pool',
    rewardedToken: 'aBNBc/BNB',
    protocol: 'PancakeSwap',
    network: 'BNB Chain',
    protocolLink:
      'https://pancakeswap.finance/info/pool/0x272c2cf847a49215a3a1d4bff8760e503a06f880',
  },

  {
    assets: 'aMATICb/wMATIC',
    type: 'Liquidity Pool',
    rewardedToken: 'aMATICb/wMATIC',
    protocol: 'Curve Finance',
    network: 'Polygon',
    protocolLink: 'https://curve.fi/ankreth/',
  },
  {
    assets: 'aMATICc/MATIC',
    type: 'Liquidity Pool',
    rewardedToken: 'aMATICc/MATIC',
    protocol: 'QuickSwap',
    network: 'Polygon',
    protocolLink:
      'https://info.quickswap.exchange/#/pair/0xe7d85cf800119bd280a2e555d3de7f954452a831',
  },
  {
    assets: 'aMATICc/MATIC',
    type: 'Liquidity Pool',
    rewardedToken: 'aMATICc/MATIC',
    protocol: 'Uniswap v3',
    network: 'Polygon',
    protocolLink:
      'https://info.uniswap.org/#/tokens/0xe95a203b1a91a908f9b9ce46459d101078c2c3cb',
  },
  {
    assets: 'aMATICc/MATIC',
    type: 'Liquidity Pool',
    rewardedToken: 'aMATICc/MATIC',
    protocol: 'Dystopia',
    network: 'Polygon',
    protocolLink:
      'https://www.dystopia.exchange/liquidity/0x29281A2B8f8Cdc453066282017C48516eC2A9d22',
  },
  {
    assets: 'aMATICb/MATIC',
    type: 'Liquidity Pool',
    rewardedToken: 'aMATICb/MATIC',
    protocol: 'ACryptoS',
    network: 'BNB Chain',
    protocolLink: 'https://app.acryptos.com/stableswap/deposit/aethb/',
  },
  {
    assets: 'aMATICb/MATIC ACryptoS LP',
    type: 'Vault',
    rewardedToken: 'aMATICb/MATIC',
    protocol: 'ACryptoS',
    network: 'BNB Chain',
    protocolLink: 'https://app.acryptos.com/stableswap/deposit/aethb/',
  },
  {
    assets: 'aMATICb/MATIC',
    type: 'Liquidity Pool',
    rewardedToken: 'aMATICb/MATIC',
    protocol: 'Ellipsis Finance',
    network: 'BNB Chain',
    protocolLink: 'https://ellipsis.finance/pool/15',
  },
  {
    assets: 'aMATICb/MATIC Ellipsis LP',
    type: 'Farming',
    rewardedToken: 'EPX',
    protocol: 'Ellipsis Finance',
    network: 'BNB Chain',
    protocolLink: 'https://ellipsis.finance/pool/15',
  },

  {
    assets: 'aAVAXb/AVAX Lydia LP',
    type: 'Liquidity Pool',
    rewardedToken: 'aAVAXb/AVAX',
    protocol: 'Curve Finance',
    network: 'Avalanche',
    protocolLink: 'https://curve.fi/ankreth/',
  },
  {
    assets: 'aAVAXb/AVAX',
    type: 'Farming',
    rewardedToken: 'LYD',
    protocol: 'Lydia Finance',
    network: 'Avalanche',
    protocolLink: 'https://www.lydia.finance/farms',
  },

  {
    assets: 'aFTMb/wFTM',
    type: 'Liquidity Pool',
    rewardedToken: 'aFTMb/wFTM',
    protocol: 'Curve Finance',
    network: 'Fantom',
    protocolLink: 'https://curve.fi/ankreth/',
  },
];
