export enum ConfirmationContentState {
  DEFAULT = 'DEFAULT',
  LOADING = 'LOADING',
  CONNECT_WALLET = 'CONNECT_WALLET',
  LINK_EXPIRED = 'LINK_EXPIRED',
  CONNECT_RELATED_WALLET = 'CONNECT_RELATED_WALLET',
}
