export enum HarmonyLibraryID {
  Harmony = 'harmony',
}

export interface HarmonyMethodResponse {}

export const HarmonyLibrary = {
  [HarmonyLibraryID.Harmony]: 'Curl',
};

export enum HarmonyMethod {
  // v2 method
  hmyv2_call = 'hmyv2_call',
  hmyv2_estimateGas = 'hmyv2_estimateGas',
  hmyv2_getCode = 'hmyv2_getCode',
  hmyv2_getStorageAt = 'hmyv2_getStorageAt',
  hmyv2_getDelegationsByDelegator = 'hmyv2_getDelegationsByDelegator',
  hmyv2_getDelegationsByValidator = 'hmyv2_getDelegationsByValidator',
  hmyv2_getAllValidatorAddresses = 'hmyv2_getAllValidatorAddresses',
  hmyv2_getAllValidatorInformation = 'hmyv2_getAllValidatorInformation',
  hmyv2_getAllValidatorInformationByBlockNumber = 'hmyv2_getAllValidatorInformationByBlockNumber',
  hmyv2_getElectedValidatorAddresses = 'hmyv2_getElectedValidatorAddresses',
  hmyv2_getValidatorInformation = 'hmyv2_getValidatorInformation',
  hmyv2_getCurrentUtilityMetrics = 'hmyv2_getCurrentUtilityMetrics',
  hmyv2_getMedianRawStakeSnapshot = 'hmyv2_getMedianRawStakeSnapshot',
  hmyv2_getStakingNetworkInfo = 'hmyv2_getStakingNetworkInfo',
  hmyv2_getSuperCommittees = 'hmyv2_getSuperCommittees',
  hmyv2_getCXReceiptByHash = 'hmyv2_getCXReceiptByHash',
  hmyv2_getPendingCXReceipts = 'hmyv2_getPendingCXReceipts',
  hmyv2_getPoolStats = 'hmyv2_getPoolStats',
  hmyv2_pendingStakingTransactions = 'hmyv2_pendingStakingTransactions',
  hmyv2_pendingTransactions = 'hmyv2_pendingTransactions',
  hmyv2_getCurrentStakingErrorSink = 'hmyv2_getCurrentStakingErrorSink',
  hmyv2_getStakingTransactionByBlockNumberAndIndex = 'hmyv2_getStakingTransactionByBlockNumberAndIndex',
  hmyv2_getStakingTransactionByBlockHashAndIndex = 'hmyv2_getStakingTransactionByBlockHashAndIndex',
  hmyv2_getStakingTransactionByHash = 'hmyv2_getStakingTransactionByHash',
  hmyv2_sendRawStakingTransaction = 'hmyv2_sendRawStakingTransaction',
  hmyv2_getCurrentTransactionErrorSink = 'hmyv2_getCurrentTransactionErrorSink',
  hmyv2_getTransactionByBlockHashAndIndex = 'hmyv2_getTransactionByBlockHashAndIndex',
  hmyv2_getTransactionByBlockNumberAndIndex = 'hmyv2_getTransactionByBlockNumberAndIndex',
  hmyv2_getTransactionByHash = 'hmyv2_getTransactionByHash',
  hmyv2_getTransactionReceipt = 'hmyv2_getTransactionReceipt',
  hmyv2_sendRawTransaction = 'hmyv2_sendRawTransaction',
  hmyv2_blockNumber = 'hmyv2_blockNumber',
  hmyv2_getCirculatingSupply = 'hmyv2_getCirculatingSupply',
  hmyv2_getEpoch = 'hmyv2_getEpoch',
  hmyv2_getLastCrossLinks = 'hmyv2_getLastCrossLinks',
  hmyv2_getLeader = 'hmyv2_getLeader',
  hmyv2_gasPrice = 'hmyv2_gasPrice',
  hmyv2_getShardingStructure = 'hmyv2_getShardingStructure',
  hmyv2_getTotalSupply = 'hmyv2_getTotalSupply',
  hmyv2_getValidators = 'hmyv2_getValidators',
  hmyv2_getValidatorKeys = 'hmyv2_getValidatorKeys',
  hmyv2_protocolVersion = 'hmyv2_protocolVersion',
  hmyv2_getBlocks = 'hmyv2_getBlocks',
  hmyv2_getBlockByNumber = 'hmyv2_getBlockByNumber',
  hmyv2_getBlockByHash = 'hmyv2_getBlockByHash',
  hmyv2_getBlockSigners = 'hmyv2_getBlockSigners',
  hmyv2_getBlockSignersKeys = 'hmyv2_getBlockSignersKeys',
  hmyv2_getBlockTransactionCountByNumber = 'hmyv2_getBlockTransactionCountByNumber',
  hmyv2_getBlockTransactionCountByHash = 'hmyv2_getBlockTransactionCountByHash',
  hmyv2_getHeaderByNumber = 'hmyv2_getHeaderByNumber',
  hmyv2_getLatestChainHeaders = 'hmyv2_getLatestChainHeaders',
  hmyv2_latestHeader = 'hmyv2_latestHeader',
  hmyv2_getBalance = 'hmyv2_getBalance',
  hmyv2_getBalanceByBlockNumber = 'hmyv2_getBalanceByBlockNumber',
  hmyv2_getStakingTransactionsCount = 'hmyv2_getStakingTransactionsCount',
  hmyv2_getStakingTransactionsHistory = 'hmyv2_getStakingTransactionsHistory',
  hmyv2_getTransactionsCount = 'hmyv2_getTransactionsCount',
  hmyv2_getTransactionsHistory = 'hmyv2_getTransactionsHistory',

  // api v1
  hmy_getBalanceByBlockNumber = 'hmy_getBalanceByBlockNumber',
  hmy_getTransactionCount = 'hmy_getTransactionCount',
  hmy_getStakingTransactionByBlockHashAndIndex = 'hmy_getStakingTransactionByBlockHashAndIndex',
  hmy_getStakingTransactionByBlockNumberAndIndex = 'hmy_getStakingTransactionByBlockNumberAndIndex',
  hmy_getStakingTransactionByHash = 'hmy_getStakingTransactionByHash',
  hmy_getCurrentTransactionErrorSink = 'hmy_getCurrentTransactionErrorSink',
  hmy_getPendingCrossLinks = 'hmy_getPendingCrossLinks',
  hmy_getPendingCXReceipts = 'hmy_getPendingCXReceipts',
  hmy_getCXReceiptByHash = 'hmy_getCXReceiptByHash',
  hmy_pendingTransactions = 'hmy_pendingTransactions',
  hmy_sendRawStakingTransaction = 'hmy_sendRawStakingTransaction',
  hmy_getTransactionsHistory = 'hmy_getTransactionsHistory',
  hmy_sendRawTransaction = 'hmy_sendRawTransaction',
  hmy_getTransactionReceipt = 'hmy_getTransactionReceipt',
  hmy_getBlockTransactionCountByHash = 'hmy_getBlockTransactionCountByHash',
  hmy_getBlockTransactionCountByNumber = 'hmy_getBlockTransactionCountByNumber',
  hmy_getTransactionByHash = 'hmy_getTransactionByHash',
  hmy_getTransactionByBlockNumberAndIndex = 'hmy_getTransactionByBlockNumberAndIndex',
  hmy_getTransactionByBlockHashAndIndex = 'hmy_getTransactionByBlockHashAndIndex',
  hmy_getBlockByNumber = 'hmy_getBlockByNumber',
  hmy_getBlockByHash = 'hmy_getBlockByHash',
  hmy_getBlocks = 'hmy_getBlocks',
  hmy_estimateGas = 'hmy_estimateGas',
  hmy_getStorageAt = 'hmy_getStorageAt',
  hmy_call = 'hmy_call',
  hmy_getCode = 'hmy_getCode',
  hmy_isLastBlock = 'hmy_isLastBlock',
  hmy_epochLastBlock = 'hmy_epochLastBlock',
  hmy_latestHeader = 'hmy_latestHeader',
  hmy_getShardingStructure = 'hmy_getShardingStructure',
  hmy_blockNumber = 'hmy_blockNumber',
  hmy_gasPrice = 'hmy_gasPrice',
  hmy_getEpoch = 'hmy_getEpoch',
  hmy_getLeader = 'hmy_getLeader',
  hmy_getCirculatingSupply = 'hmy_getCirculatingSupply',
  hmy_getTotalSupply = 'hmy_getTotalSupply',
  hmy_getStakingNetworkInfo = 'hmy_getStakingNetworkInfo',
  hmy_getAllValidatorInformation = 'hmy_getAllValidatorInformation',
  hmy_getAllValidatorInformationByBlockNumber = 'hmy_getAllValidatorInformationByBlockNumber',
  hmy_getCurrentUtilityMetrics = 'hmy_getCurrentUtilityMetrics',
  hmy_getDelegationsByValidator = 'hmy_getDelegationsByValidator',
  hmy_getDelegationsByDelegatorAndValidator = 'hmy_getDelegationsByDelegatorAndValidator',
  hmy_getDelegationsByDelegator = 'hmy_getDelegationsByDelegator',
  hmy_getValidatorMetrics = 'hmy_getValidatorMetrics',
  hmy_getMedianRawStakeSnapshot = 'hmy_getMedianRawStakeSnapshot',
  hmy_getActiveValidatorAddresses = 'hmy_getActiveValidatorAddresses',
  hmy_getAllValidatorAddresses = 'hmy_getAllValidatorAddresses',
  hmy_getCurrentStakingErrorSink = 'hmy_getCurrentStakingErrorSink',
  hmy_getValidatorInformation = 'hmy_getValidatorInformation',
  hmy_getValidators = 'hmy_getValidators',
  hmy_getSignedBlocks = 'hmy_getSignedBlocks',
  hmy_isBlockSigner = 'hmy_isBlockSigner',
  hmy_getBlockSigners = 'hmy_getBlockSigners',
}
