export enum Token {
  ETH = 'ETH',
  aETHb = 'aETHb',
  aETH = 'aETH',
  aETHc = 'aETHc',
  asETHc = 'asETHc',
  AVAX = 'AVAX',
  aAVAXb = 'aAVAXb',
  aAVAXc = 'aAVAXc',
  MATIC = 'MATIC',
  aMATICb = 'aMATICb',
  aMATICc = 'aMATICc',
  BNB = 'BNB',
  aBNBb = 'aBNBb',
  aBNBc = 'aBNBc',
  FTM = 'FTM',
  aFTMb = 'aFTMb',
  aFTMc = 'aFTMc',
  DOT = 'DOT',
  aDOTb = 'aDOTb',
  KSM = 'KSM',
  aKSMb = 'aKSMb',
  WND = 'WND',
  aWNDb = 'aWNDb',
  ANKR = 'ANKR',
  mGNO = 'mGNO',
  xDAI = 'xDAI',
}
