export enum Token {
  ETH = 'ETH',
  aETHb = 'aETHb',
  aETHc = 'aETHc',
  AVAX = 'AVAX',
  aAVAXb = 'aAVAXb',
  MATIC = 'MATIC',
  aMATICb = 'aMATICb',
  BNB = 'BNB',
  aBNBb = 'aBNBb',
  aBNBc = 'aBNBc',
  FTM = 'FTM',
  aFTMb = 'aFTMb',
  DOT = 'DOT',
  aDOTb = 'aDOTb',
  KSM = 'KSM',
  aKSMb = 'aKSMb',
  WND = 'WND',
  aWNDb = 'aWNDb',
}
