name: MRPC Admin panel deploy

on:
  workflow_dispatch:
    inputs:
      domain:
        type: choice
        description: Target
        required: true
        options:
          - STAGE #https://multirpc-backoffice-stage.dccn.ankr.com/
          - PROD  #https://multirpc-backoffice.dccn.ankr.com/
      api:
        type: choice
        description: API
        required: true
        options:
          - STAGE
          - PROD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: egordm/gha-yarn-node-cache@v1
      - uses: nelonoel/branch-name@v1.0.1

      - name: Get deployment information
        run: |
          echo "Branch: ${{github.ref}}"
          echo "Domain: ${{github.event.inputs.domain}}"
          echo "API: ${{github.event.inputs.api}}"

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16.13.0'

      - name: Install dependencies
        run: |
          rm -rf node_modules/.cache
          yarn install

      - name: Build stage
        working-directory: ./packages/admin-mrpc
        if: ${{ github.event.inputs.api == 'STAGE' }}
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        run: |
          yarn build:stage:turbo
          yarn postbuild

      - name: Build production
        working-directory: ./packages/admin-mrpc
        if: ${{ github.event.inputs.api == 'PROD' }}
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: |
          yarn build:prod:turbo
          yarn postbuild

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy files to the production website with the AWS CLI
        working-directory: ./packages/admin-mrpc
        env:
          DOMAIN: ${{ secrets[format('{0}{1}{2}', 'MULTIRPC_BACKOFFICE_', github.event.inputs.domain, '_DOMAIN')] }}
          DISTRIBUTION_ID: ${{ secrets[format('{0}{1}{2}', 'MULTIRPC_BACKOFFICE_', github.event.inputs.domain, '_DISTRIBUTION_ID')] }}
        run: |
          aws s3 sync --delete ./build s3://$DOMAIN/ --acl public-read --cache-control "public,max-age=600,s-maxage=3600"
          aws configure set preview.cloudfront true
          echo "Invalidating CDN network"
          INVALIDATION_ID=`aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*' | jq -r '.Invalidation.Id'`
          echo "Invalidation ID is $INVALIDATION_ID"
          echo "CDN Invalidation request is sent."
