name: Run build and tests
on:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup caching for dependencies
        uses: egordm/gha-yarn-node-cache@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16.13.0'

      - name: Install dependencies
        run: yarn install

      - name: Build & lint
        working-directory: .
        run: lerna run build

      # TODO: Test coverage must be less or equal to previous
      - name: Tests
        working-directory: ./packages/ankr-earn
        run: yarn test:coverage
