name: Run build and tests
on:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup caching for dependencies
        uses: egordm/gha-yarn-node-cache@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16.13.0'

      - name: Install dependencies
        run: yarn install

      - name: Build libs
        working-directory: .
        run: |
          lerna run build

      - name: Build apps
        working-directory: .
        run: |
          lerna run build:prod

      - name: Tests
        working-directory: ./packages/ankr-earn
        run: yarn test:coverage
