name: Run build and tests
on:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build libs
        working-directory: .
        run: |
          lerna run build

      - name: Build apps
        working-directory: .
        run: |
          lerna run build:prod

      - name: Tests
        working-directory: ./packages/ankr-earn
        run: yarn test:coverage
