name: Health Check Stage
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # run every day

defaults:
  run:
    working-directory: ./packages/standalone-protocol/tests/e2e

jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: xvfb-run yarn test:healthCheck

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-artifacts
          if-no-files-found: ignore
          retention-days: 1
          path: ./packages/standalone-protocol/tests/e2e/test-results
